import type { Metadata } from 'next'
import "./styles/globals.scss";
import { Navbar } from "./components/views/navbar";
import { Poppins } from "next/font/google";
import { Footer } from "./components/views/footer";
import { ShoppingCart } from "./components/views/shoppingcart/shoppingcart";
import { Providers } from './storeProvider';
import { GlobalContextProvider } from './context/globalcontext';


const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Providers>
          <GlobalContextProvider>
            <Navbar />
            {children}
            <Footer />
          </GlobalContextProvider>
        </Providers>
      </body>
    </html>
  );
}
